version: '3.5'

services:
  gitlab:
    image: gitlab/gitlab-ce
    ports:
    - '9090:9090'
    volumes:
    - gitlab-config:/etc/gitlab
    - gitlab-data:/var/opt/gitlab
    configs:
    - source: gitlab-rb
      target: /etc/gitlab/gitlab.rb    
    deploy:
      placement:
        constraints:
         - node.hostname == docker2

volumes:
  gitlab-data: {}
  gitlab-config: {}

configs:
  gitlab-rb:
    file: ./gitlab.rb
