version: '3.5'

services:
  jenkins:
    image: jenkins/jenkins-lts
    ports:
    - '8080:8080'
    volumes:
    - jenkins-home:/var/jenkins_home
    deploy:
      placement:
        constraints:
         - node.hostname == docker3

volumes:
  jenkins-home: {}
